name: Beta Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  beta-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo clean
    - name: Build persistence
      run: cargo build --verbose
    - name: Run tests persistence
      run: cargo test --verbose
    - run: cargo clean
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
